name: windows-x64

on: 
  push:
    branches: [ mybranch87_0_4272_0 ]

jobs:
  build-windows-x64:
    runs-on: windows-2022
    steps:
      - name: info1
        shell: cmd
        run: |
          cmd /c "echo hello_clean1"
      - name: Install Required Dependencies
        if: true
        shell: cmd
        run: |
          curl -sOL https://aka.ms/vs/16/release/vs_community.exe
          .\vs_community.exe --passive --wait --norestart --nocache --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community" --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
      - name: info2
        shell: bash
        run: |
          echo hello_clean2
          ls 
          pwd
          rm -rf *
          ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community"
          echo hello_clean2
      - name: Checkout sources
        run: |
          git clone https://github.com/kimown/angle .
          git checkout mybranch87_0_4272_0
      - name: Fetchfea depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Install Python3 to D
        run: |
          curl -LO https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip
          mkdir D:\a\angle\angle\python3
          powershell -Command "Expand-Archive -Path python-3.11.9-embed-amd64.zip -DestinationPath D:\a\angle\angle\python3"
      - name: info3
        shell: bash
        run: |
          ls 
          pwd
          ls "/d/a/angle/angle/python3"
          ls "/d/a/angle/angle/build"
      - name: Build
        shell: cmd
        run: |
          cmd /c python --version
          set PATH=%cd%\python3;%cd%\depot_tools;%PATH%
          cmd /c python --version
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
          set WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
          cmd /c gclient
          cmd /c python scripts/bootstrap.py
          set PYTHONPATH=%cd%\build
          cmd /c gclient sync
          cmd /c gn gen out/Release --args="is_debug=false target_cpu=\"x64\" angle_build_all=false"
          cmd /c autoninja -C out/Release
      - name: Pack
        shell: bash
        run: |
          mkdir angle-windows-x64
          mkdir angle-windows-x64/dist
          rm -rf out/Release/cdb
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          rm -rf out/Release/args.gn
          rm -rf out/Release/build.ninja
          rm -rf out/Release/build.ninja.d
          rm -rf out/Release/toolchain.ninja
          rm -rf out/Release/environment.*
          find out/Release -name "*.pdb" -delete
          mv -f out/Release/* angle-windows-x64/dist/
          cp -rf include angle-windows-x64/
          find angle-windows-x64 -name ".clang-format" -delete
          find angle-windows-x64 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angle-windows-x64
          path: angle-windows-x64